{{- if .Values.networkPolicies.enable }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "cas-ciip-2018-extract.name" . }}-ciip-access
  labels: {{ include "cas-ciip-2018-extract.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      release: {{ .Values.ciip.release }}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: {{ include "cas-ciip-2018-extract.namespacePrefix" . }}
          environment: {{ include "cas-ciip-2018-extract.namespaceSuffix" . }}
      podSelector:
        matchLabels:
          app.kubernetes.io/instance: {{ include "cas-ciip-2018-extract.name" . }}
{{- end }}
