{{- if .Values.networkSecurityPolicies.enable }}
kind: NetworkSecurityPolicy
apiVersion: security.devops.gov.bc.ca/v1alpha1
metadata:
  name: {{ include "cas-ciip-2018-extract.name" . }}-egress
  labels: {{ include "cas-ciip-2018-extract.labels" . | nindent 4 }}
spec:
  description: allow the trigger pod to talk to do REST requests on airflow public URLs
  source:
    - - $namespace={{ .Release.Namespace }}
      - app.kubernetes.io/instance={{ include "cas-ciip-2018-extract.name" . }}
  destination:
    - - 'ext:network=any'
{{- end }}