{{- if and .Values.swrsImportBucket.enable .Values.networkSecurityPolicies.enable }}
kind: NetworkSecurityPolicy
apiVersion: security.devops.gov.bc.ca/v1alpha1
metadata:
  name: {{ include "cas-ciip-2018-extract.fullname" . }}-cas-shelf
  labels: {{ include "cas-ciip-2018-extract.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "hook-succeeded,hook-failed"
    "helm.sh/hook-weight": "-100"
spec:
  description: allow the cas-shelf provider job within this release to communicate with external networks
  source:
    - - $namespace={{ .Release.Namespace }}
      - app.kubernetes.io/instance={{ include "cas-ciip-2018-extract.name" . }}
  destination:
    - - ext:network=any
{{- end }}
