apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: job-template

parameters:
- description: Prefix to prepend to object name.
  displayName: Prefix
  name: PREFIX
  required: true
- description: SHA1 of git revision to be deployed.
  displayName: Git SHA1
  name: GIT_SHA1
  required: true
- description: Openshift project name
  displayName: Project
  name: OC_PROJECT
  required: true
- description: Openshift registry URL
  displayName: Registry
  name: OC_REGISTRY
  required: true

objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    annotations:
      template.alpha.openshift.io/wait-for-ready: "true"
    name: ${PREFIX}ciip-2018-extract
  spec:
    parallelism: 1
    completions: 1
    backoffLimit: 0
    activeDeadlineSeconds: 1200
    template:
      metadata:
        name: ${PREFIX}ciip-2018-extract
      spec:
        restartPolicy: Never
        containers:
        - env:
          - name: PGUSER
            valueFrom:
              secretKeyRef:
                key: database-user
                name: ${PREFIX}postgres
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                key: database-password
                name: ${PREFIX}postgres
          - name: PGDATABASE
            valueFrom:
              secretKeyRef:
                key: database-name
                name: ${PREFIX}postgres
          - name: PGHOST
            value: ${PREFIX}postgres
          - name: APP_SCRIPT
            value: "run-extract.sh"
          - name: CIIP_FILES_DIR
            value: "/opt/app-root/src/data/CIIP applications_2018/CIIP data_final"
          image: ${OC_REGISTRY}/${OC_PROJECT}/${PREFIX}ciip-2018-extract:${GIT_SHA1}
          name: ${PREFIX}ciip-2018-extract
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
          volumeMounts:
            - mountPath: /opt/app-root/src/data
              name: ${PREFIX}ciip-2018-data
        volumes:
        - name: ${PREFIX}ciip-2018-data
          persistentVolumeClaim:
            claimName: ${PREFIX}ciip-2018-data
