apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: deploy-template

parameters:
- description: Prefix to prepend to object name.
  displayName: Prefix
  name: PREFIX
  required: true
- description: SHA1 of git revision to be deployed.
  displayName: Git SHA1
  name: GIT_SHA1
  required: true


envDefaults: &envDefaults
  env:
    - name: PGUSER
      valueFrom:
        secretKeyRef:
          key: database-user
          name: ${PREFIX}postgres
    - name: PGPASSWORD
      valueFrom:
        secretKeyRef:
          key: database-password
          name: ${PREFIX}postgres
    - name: PGDATABASE
      valueFrom:
        secretKeyRef:
          key: database-name
          name: ${PREFIX}postgres
    - name: PGHOST
      value: ${PREFIX}postgres
    - name: APP_SCRIPT
      value: "run-extract.sh"

objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      template.alpha.openshift.io/wait-for-ready: "true"
    name: ${PREFIX}extract
  spec:
    replicas: 1
    selector:
      name: ${PREFIX}extract
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: ${PREFIX}extract
      spec:
        containers:
        - <<: *envDefaults
          image: ${PREFIX}extract:${GIT_SHA1}
          imagePullPolicy: IfNotPresent
          name: ${PREFIX}extract
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /opt/app-root/src/data
            name: ${PREFIX}data
          - mountPath: /opt/configs
            name: ciip-extract-dirlist
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        volumes:
        - name: ${PREFIX}data
          persistentVolumeClaim:
            claimName: ${PREFIX}data
        - configMap:
            defaultMode: 420
            name: ciip-extract-dirlist
          name: ciip-extract-dirlist
    triggers: []
