apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: deploy-template

parameters:
- description: Prefix to prepend to object name.
  displayName: Prefix
  name: PREFIX
  required: true
- description: SHA1 of git revision to be deployed.
  displayName: Git SHA1
  name: GIT_SHA1
  required: true
- description: Openshift project name
  displayName: Project
  name: OC_PROJECT
  required: true
- description: Openshift registry URL
  displayName: Registry
  name: OC_REGISTRY
  required: true


envDefaults: &envDefaults
  env:
    - name: PGUSER
      valueFrom:
        secretKeyRef:
          key: database-user
          name: ${PREFIX}postgres
    - name: PGPASSWORD
      valueFrom:
        secretKeyRef:
          key: database-password
          name: ${PREFIX}postgres
    - name: PGDATABASE
      valueFrom:
        secretKeyRef:
          key: database-name
          name: ${PREFIX}postgres
    - name: PGHOST
      value: ${PREFIX}postgres
    - name: APP_SCRIPT
      value: "run-extract.sh"
    - name: CIIP_FILES_DIR
      value: "/opt/app-root/src/data/CIIP applications_2018/Complete CIIP data"

objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      template.alpha.openshift.io/wait-for-ready: "true"
    name: ${PREFIX}ciip-2018-extract
  spec:
    replicas: 1
    selector:
      name: ${PREFIX}ciip-2018-extract
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: ${PREFIX}ciip-2018-extract
      spec:
        containers:
        - <<: *envDefaults
          image: ${OC_REGISTRY}/${OC_PROJECT}/${PREFIX}ciip-2018-extract:${GIT_SHA1}
          imagePullPolicy: IfNotPresent
          name: ${PREFIX}ciip-2018-extract
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /opt/app-root/src/data
            name: ${PREFIX}ciip-2018-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        volumes:
        - name: ${PREFIX}ciip-2018-data
          persistentVolumeClaim:
            claimName: ${PREFIX}ciip-2018-data
